name: build script for hello.c		

on:							
  push:
    branches: [ "main" ]			

jobs:
  build:						
    runs-on: ubuntu-latest			
    steps:
      - uses: actions/checkout@v4		

      - name: build quiz			
        run: gcc -o quiz quiz.c		

      - name: upload binary			
        uses: actions/upload-artifact@v4	
        with:
          name: Quiz game		
          path: ./quiz			

